### ISSUE TITLE
如何处理willTransitionTo函数的问题？

### ISSUE THREAD

**Issue by code-tinker** [hufeng/react-async-router#1]
RT~
react-router只会去调用asyncLoader的willTransitionTo函数，而异步加载进来的页面的willTransitionTo都不会被调用

**Comment by hufeng** [comment]
3ks反馈，我来研究下willTransitonTo具体的功能。我们现在还没有用到willTransitionTo

**Comment by hufeng** [comment]
在想，在参数component上加个ref，去获取组件的对象的静态方法 判断是不是有willTranstionTo和willTranstionFrom, 有做一个合并

**Comment by code-tinker** [comment]
有可能情况比纯粹的合并要复杂一些，因为如果在页面里的willTransitionTo做了重定向abort等操作，不知道会不会有问题。
因为react-router的willTransitionTo在官方是给我们一个重定向页面或者abort的机会，如果在willTransitionTo里abort了，那么在router history里面应该是没有记录的，但是在react－async－router里，即使页面abort了，但是其实由于异步的原因，其实react－router认为已经进入了页面。

**Comment by hufeng** [comment]
恩。明白您的意思，还是等react-router1.0吧。现在已经是beta3，彻底的解决了ie兼容性，以及对异步的支持。非常值得期待。
