### ISSUE TITLE
生成的异步 bundle 文件跑在HistoryLocation模式下路径出错

### ISSUE THREAD

**Issue by Lucifier129** [hufeng/react-async-router#2]
这个看起来跟 webpack 有关

script.src = **webpack_require**.p + "" + chunkId + ".bundle.js";

_webpack_require__.p 是固定路径吗？

可以配置为指定的绝对路径吗？

**Comment by Lucifier129** [comment]
已经解决这个问题，请关闭吧。

配置 publicPath 就可以了。

**Comment by Lucifier129** [comment]
另一个问题是，即便用了bundle-loader 也无法解决 webpack 不能 require/import 变量模块的问题，是吗？

**Comment by hufeng** [comment]
变量模块，是什么意思？

**Comment by Lucifier129** [comment]
"参数不能是表达式"这个问题有解决方案吗？

**Comment by Lucifier129** [comment]
另外还有一个问题：
https://github.com/QianmiOpen/react-async-router/blob/master/assets/apps/async-loader.js

async-loader 目前的实现没有考虑 react-router 的 willTransitionTo / willTransitionFrom 静态方法

**Comment by Lucifier129** [comment]
https://github.com/Lucifier129/webpack-workflow/blob/master/src/asyncComponent.js

我依据你这个项目改造了一个工作流体验项目，在看过 react-router 的文档后，发现它在 v1.0 版本的 api 发生了巨大变化，目前文档也还在完善中。

所以打算等待 react-router v1.0 成熟后，再结合 reactv0.14 + ralay + graphql 重新整理一个工作流。

**Comment by hufeng** [comment]
是的，我也是很期待1.0，api变化很大，而且解决了很多比较棘手的问题，比如IE8的兼容性，以及异步的模块加载方案，目前react-router@0.13.3对IE8支持的非常烂，我也是在等待1.0 然后把目前的代码迁移到1.0. :) 很快我们现在的方案就是过去式，但这不重要，重要的是我们迎来了更好的生态。

**Comment by hufeng** [comment]
也期待到时候看到您react@0.14.4 + relay + graphql的分享

**Comment by Lucifier129** [comment]
互相学习：）
